#!/bin/bash
root -q -b ytMllPlot.C"(\"TightLLH\",\"isolTight\")"
root -q -b ytMllPlot.C"(\"TightLLH\",\"isolLoose\")"
root -q -b ytMllPlot.C"(\"TightLLH\",\"isolLooseTrackOnly\")"
root -q -b ytMllPlot.C"(\"TightLLH\",\"isolGradient\")"
root -q -b ytMllPlot.C"(\"TightLLH\",\"isolGradientLoose\")"
root -q -b ytMllPlot.C"(\"TightLLH\",\"isolFixedCutTightTrackOnly\")"
root -q -b ytMllPlot.C"(\"TightLLH\",\"isolFixedCutTight\")"
root -q -b ytMllPlot.C"(\"TightLLH\",\"isolFixedCutLoose\")"

root -q -b yt2DPlots.C"(\"TightLLH\",\"isolTight\")"
root -q -b yt2DPlots.C"(\"TightLLH\",\"isolLoose\")"
root -q -b yt2DPlots.C"(\"TightLLH\",\"isolLooseTrackOnly\")"
root -q -b yt2DPlots.C"(\"TightLLH\",\"isolGradient\")"
root -q -b yt2DPlots.C"(\"TightLLH\",\"isolGradientLoose\")"
root -q -b yt2DPlots.C"(\"TightLLH\",\"isolFixedCutTightTrackOnly\")"
root -q -b yt2DPlots.C"(\"TightLLH\",\"isolFixedCutTight\")"
root -q -b yt2DPlots.C"(\"TightLLH\",\"isolFixedCutLoose\")"

root -q -b yt1DEffPlots.C"(\"TightLLH\",\"isolTight\")"
root -q -b yt1DEffPlots.C"(\"TightLLH\",\"isolLoose\")"
root -q -b yt1DEffPlots.C"(\"TightLLH\",\"isolLooseTrackOnly\")"
root -q -b yt1DEffPlots.C"(\"TightLLH\",\"isolGradient\")"
root -q -b yt1DEffPlots.C"(\"TightLLH\",\"isolGradientLoose\")"
root -q -b yt1DEffPlots.C"(\"TightLLH\",\"isolFixedCutTightTrackOnly\")"
root -q -b yt1DEffPlots.C"(\"TightLLH\",\"isolFixedCutTight\")"
root -q -b yt1DEffPlots.C"(\"TightLLH\",\"isolFixedCutLoose\")"

root -q -b yt1DSFPlots.C"(\"TightLLH\",\"isolTight\")"
root -q -b yt1DSFPlots.C"(\"TightLLH\",\"isolLoose\")"
root -q -b yt1DSFPlots.C"(\"TightLLH\",\"isolLooseTrackOnly\")"
root -q -b yt1DSFPlots.C"(\"TightLLH\",\"isolGradient\")"
root -q -b yt1DSFPlots.C"(\"TightLLH\",\"isolGradientLoose\")"
root -q -b yt1DSFPlots.C"(\"TightLLH\",\"isolFixedCutTightTrackOnly\")"
root -q -b yt1DSFPlots.C"(\"TightLLH\",\"isolFixedCutTight\")"
root -q -b yt1DSFPlots.C"(\"TightLLH\",\"isolFixedCutLoose\")"

root -q -b ytRatioPlots.C"(\"TightLLH\",\"isolTight\")"
root -q -b ytRatioPlots.C"(\"TightLLH\",\"isolLoose\")"
root -q -b ytRatioPlots.C"(\"TightLLH\",\"isolLooseTrackOnly\")"
root -q -b ytRatioPlots.C"(\"TightLLH\",\"isolGradient\")"
root -q -b ytRatioPlots.C"(\"TightLLH\",\"isolGradientLoose\")"
root -q -b ytRatioPlots.C"(\"TightLLH\",\"isolFixedCutTightTrackOnly\")"
root -q -b ytRatioPlots.C"(\"TightLLH\",\"isolFixedCutTight\")"
root -q -b ytRatioPlots.C"(\"TightLLH\",\"isolFixedCutLoose\")"

root -q -b ytCompareSFPlots.C"(\"TightLLH\",\"isolTight\")"
root -q -b ytCompareSFPlots.C"(\"TightLLH\",\"isolLoose\")"
root -q -b ytCompareSFPlots.C"(\"TightLLH\",\"isolLooseTrackOnly\")"
root -q -b ytCompareSFPlots.C"(\"TightLLH\",\"isolGradient\")"
root -q -b ytCompareSFPlots.C"(\"TightLLH\",\"isolGradientLoose\")"
root -q -b ytCompareSFPlots.C"(\"TightLLH\",\"isolFixedCutTightTrackOnly\")"
root -q -b ytCompareSFPlots.C"(\"TightLLH\",\"isolFixedCutTight\")"
root -q -b ytCompareSFPlots.C"(\"TightLLH\",\"isolFixedCutLoose\")"
